#include <iostream>
#include <conio.h>
using namespace std;

int main()
{
string "text"; // mendefinisikan var z sebagai variabel integer

	
      cout<< "        Hallo TEMAN-TEMAN Welcome to Borland C++.\n";
      cout<< "           Masukkan nama: ";
      cin>> "text" ; // Memasukkan sebuah nilai yang akan disimpan dalam var z 
       // clrs; Membersihkan perintah sebelumnya pada layar
      cout<< "  Nilai yang anda masukkan adalah : "<< "text" << endl; //menampilkan isi var z
      cout<< "                    Programmer By : Mahasiswa Perdana\n";
      cout<< "                              NIM :  20050718\n";
      cout<< "                             STIMIK PROFESIONAL";
	getch;
}


